import { IData, IRawData } from './type';
export const convertData = (raw: IRawData): IData => ({
    fileGenerationDate: raw.fileGenerationDate,
    Entity: {
        LogicalId: raw.Entity_LogicalId,
        EU_ReferenceNumber: raw.Entity_EU_ReferenceNumber,
        UnitedNationId: raw.Entity_UnitedNationId,
        DesignationDate: raw.Entity_DesignationDate,
        DesignationDetails: raw.Entity_DesignationDetails,
        Remark: raw.Entity_Remark,
        SubjectType: raw.Entity_SubjectType,
        SubjectType_ClassificationCode: raw.Entity_SubjectType_ClassificationCode,
        Regulation: {
            Type: raw.Entity_Regulation_Type,
            OrganisationType: raw.Entity_Regulation_OrganisationType,
            PublicationDate: raw.Entity_Regulation_PublicationDate,
            EntryIntoForceDate: raw.Entity_Regulation_EntryIntoForceDate,
            NumberTitle: raw.Entity_Regulation_NumberTitle,
            Programme: raw.Entity_Regulation_Programme,
            PublicationUrl: raw.Entity_Regulation_PublicationUrl,
        }
    },
    NameAlias: {
        LastName: raw.NameAlias_LastName,
        FirstName: raw.NameAlias_FirstName,
        MiddleName: raw.NameAlias_MiddleName,
        WholeName: raw.NameAlias_WholeName,
        NameLanguage: raw.NameAlias_NameLanguage,
        Gender: raw.NameAlias_Gender,
        Title: raw.NameAlias_Title,
        Function: raw.NameAlias_Function,
        LogicalId: raw.NameAlias_LogicalId,
        RegulationLanguage: raw.NameAlias_RegulationLanguage,
        Remark: raw.NameAlias_Remark,
        Regulation: {
            Type: raw.NameAlias_Regulation_Type,
            OrganisationType: raw.NameAlias_Regulation_OrganisationType,
            PublicationDate: raw.NameAlias_Regulation_PublicationDate,
            EntryIntoForceDate: raw.NameAlias_Regulation_EntryIntoForceDate,
            NumberTitle: raw.NameAlias_Regulation_NumberTitle,
            Programme: raw.NameAlias_Regulation_Programme,
            PublicationUrl: raw.NameAlias_Regulation_PublicationUrl,
        },
    },
    Address: {
        City: raw.Address_City,
        Street: raw.Address_Street,
        PoBox: raw.Address_PoBox,
        ZipCode: raw.Address_ZipCode,
        Region: raw.Address_Region,
        Place: raw.Address_Place,
        AsAtListingTime: raw.Address_AsAtListingTime,
        ContactInfo: raw.Address_ContactInfo,
        CountryIso2Code: raw.Address_CountryIso2Code,
        CountryDescription: raw.Address_CountryDescription,
        LogicalId: raw.Address_LogicalId,
        RegulationLanguage: raw.Address_RegulationLanguage,
        Remark: raw.Address_Remark,
        Regulation: {
            Type: raw.Address_Regulation_Type,
            OrganisationType: raw.Address_Regulation_OrganisationType,
            PublicationDate: raw.Address_Regulation_PublicationDate,
            EntryIntoForceDate: raw.Address_Regulation_EntryIntoForceDate,
            NumberTitle: raw.Address_Regulation_NumberTitle,
            Programme: raw.Address_Regulation_Programme,
            PublicationUrl: raw.Address_Regulation_PublicationUrl,
        }
    },
    BirthDate: {
        BirthDate: raw.BirthDate_BirthDate,
        Day: raw.BirthDate_Day,
        Month: raw.BirthDate_Month,
        Year: raw.BirthDate_Year,
        YearRangeFrom: raw.BirthDate_YearRangeFrom,
        YearRangeTo: raw.BirthDate_YearRangeTo,
        Circa: raw.BirthDate_Circa,
        CalendarType: raw.BirthDate_CalendarType,
        ZipCode: raw.BirthDate_ZipCode,
        Region: raw.BirthDate_Region,
        Place: raw.BirthDate_Place,
        City: raw.BirthDate_City,
        CountryIso2Code: raw.BirthDate_CountryIso2Code,
        CountryDescription: raw.BirthDate_CountryDescription,
        LogicalId: raw.BirthDate_LogicalId,
        RegulationLanguage: raw.BirthDate_RegulationLanguage,
        Remark: raw.BirthDate_Remark,
        Regulation: {
            Type: raw.BirthDate_Regulation_Type,
            OrganisationType: raw.BirthDate_Regulation_OrganisationType,
            PublicationDate: raw.BirthDate_Regulation_PublicationDate,
            EntryIntoForceDate: raw.BirthDate_Regulation_EntryIntoForceDate,
            NumberTitle: raw.BirthDate_Regulation_NumberTitle,
            Programme: raw.BirthDate_Regulation_Programme,
            PublicationUrl: raw.BirthDate_Regulation_PublicationUrl,
        },
    },
    Identification: {
        Number: raw.Identification_Number,
        Diplomatic: raw.Identification_Diplomatic,
        KnownExpired: raw.Identification_KnownExpired,
        KnownFalse: raw.Identification_KnownFalse,
        ReportedLost: raw.Identification_ReportedLost,
        RevokedByIssuer: raw.Identification_RevokedByIssuer,
        IssuedBy: raw.Identification_IssuedBy,
        IssuedDate: raw.Identification_IssuedDate,
        ValidFrom: raw.Identification_ValidFrom,
        ValidTo: raw.Identification_ValidTo,
        LatinNumber: raw.Identification_LatinNumber,
        NameOnDocument: raw.Identification_NameOnDocument,
        TypeCode: raw.Identification_TypeCode,
        TypeDescription: raw.Identification_TypeDescription,
        Region: raw.Identification_Region,
        CountryIso2Code: raw.Address_CountryIso2Code,
        CountryDescription: raw.Identification_CountryDescription,
        LogicalId: raw.Identification_LogicalId,
        RegulationLanguage: raw.Identification_RegulationLanguage,
        Remark: raw.Identification_Remark,
        Regulation: {
            Type: raw.Identification_Regulation_Type,
            OrganisationType: raw.Identification_Regulation_OrganisationType,
            PublicationDate: raw.Identification_Regulation_PublicationDate,
            EntryIntoForceDate: raw.Identification_Regulation_EntryIntoForceDate,
            NumberTitle: raw.Identification_Regulation_NumberTitle,
            Programme: raw.Identification_Regulation_Programme,
            PublicationUrl: raw.Identification_Regulation_PublicationUrl,
        }
    },
    Citizenship: {
        Region: raw.Citizenship_Region,
        CountryIso2Code: raw.Citizenship_CountryIso2Code,
        CountryDescription: raw.Citizenship_CountryDescription,
        LogicalId: raw.Address_LogicalId,
        RegulationLanguage: raw.Citizenship_RegulationLanguage,
        Remark: raw.Citizenship_Remark,
        Regulation: {
            Type: raw.Citizenship_Regulation_Type,
            OrganisationType: raw.Citizenship_Regulation_OrganisationType,
            PublicationDate: raw.Citizenship_Regulation_PublicationDate,
            EntryIntoForceDate: raw.Citizenship_Regulation_EntryIntoForceDate,
            NumberTitle: raw.Citizenship_Regulation_NumberTitle,
            Programme: raw.Citizenship_Regulation_Programme,
            PublicationUrl: raw.Citizenship_Regulation_PublicationUrl,
        },
    }

})